name: Tinyfeed build & deploy
on:
  schedule:           # runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # manual trigger button
  push:              # trigger on push to main branch
    branches:
      - main

# Permissões necessárias para o GitHub Pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tinyfeed
        run: |
          wget https://github.com/TheBigRoomXXL/tinyfeed/releases/latest/download/tinyfeed_linux_amd64 -O /usr/local/bin/tinyfeed
          chmod +x /usr/local/bin/tinyfeed
          # Diagnóstico do arquivo baixado
          echo "Verificando o tipo de arquivo:"
          file /usr/local/bin/tinyfeed
          echo "Primeiras linhas do arquivo (pode ser binário):"
          head -n 5 /usr/local/bin/tinyfeed || true

      - name: Create output directory
        run: mkdir -p public

      - name: Generate site
        run: |
          tinyfeed \
            --input feeds.txt \
            --output public/index.html \
            --limit 100 \
            --limit-per-feed 20 \
            --name "AI News Feed" \
            --description "A collection of AI and technology news feeds"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public 